name: test-gh-actions
run-name: ${{ github.actor }} Using GH actions.
on:
  workflow_dispatch:
  push:
    branches:
      - my_branch

jobs:
  add-note:
    name: add notes to file called workflow.txt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0


      - name: display
        run: |
          git branch
      - name: add the note to file
        run: |
          git config  user.email "mahmoudshabban300@gmail.com"
          git config  user.name "GH Actions"
          ls
          echo "here we should be building and testing the code"




      - name: merge into main
        run: |
          git branch --track main origin/main
          git checkout main
          git branch
          git merge --no-ff my_branch
          git status


      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_ACTIONS_PAT }}
          branch: main

    
