name: test-gh-actions
run-name: ${{ github.actor }} Using GH actions.
on:
  workflow_dispatch:
  push:
    branches:
      - my_branch

jobs:
  add-note:
    name: add notes to file called workflow.txt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0


      - name: display
        run: |
          git branch
      - name: add the note to file
        run: |
          git config  user.email "mahmoudshabban300@gmail.com"
          git config  user.name "GH Actions"
          echo "add by workflow at $(date)" >> workflow.note
          git add .
          git commit -am "added from workflow"

      # - name: checkout main
      #   uses: actions/checkout@v4
      #   with: 
      #     persist-credentials: false
      #     ref: main

      # - name: merge in main
      #   run: |
      #     git branch
      #     git merge --no-ff --allow-unrelated-histories -m "github actions" origin/my_branch

      - name: merge into main
        run: |
          git branch -t main origin/main
          git checkout main
          git branch
          git merge --no-ff my_branch
          git status
          cat .github/workflow/test.yaml
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_ACTIONS_PAT }}
          branch: main

      # - name: Merge branch
      #   uses: julbme/gh-action-merge-branch@v1
      #   with:
      #     from: ${{ github.ref }}
      #     to: main
      #     message: Merge commit message
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}   
      #     branch: main
  
